user                "DrDDrake"
music_directory     "/home/DrDDrake/Music"
db_file             "/home/DrDDrake/.local/state/mpd/database"
log_file            "/home/DrDDrake/.local/state/mpd/log"
pid_file            "/home/DrDDrake/.local/state/mpd/pid"
state_file          "/home/DrDDrake/.local/state/mpd/state"
sticker_file        "/home/DrDDrake/.local/state/mpd/sticker.sql"

audio_output {
    type            "alsa"
    name            "DAC USB-C (Bit Perfect)"
    device          "hw:CARD=Odo,DEV=0"
    mixer_type      "none"
}
audio_output {
    type        "pulse"
    name        "System Output"
    server      "/run/user/1000/pulse/native"
}
replaygain          "off"
